swagger: "2.0"
info:
    title: predictions
    description: crop yield monitor
    version: ""
host: 0.0.0.0:8082
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /healthz:
        get:
            tags:
                - servers
            summary: get health servers
            operationId: servers#get health
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ServersGetHealthResponseBody'
            schemes:
                - http
    /openapi3.json:
        get:
            tags:
                - servers
            summary: Download ./gen/http/openapi3.json
            operationId: servers#/openapi3.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
    /predict:
        get:
            tags:
                - servers
            summary: predict servers
            operationId: servers#predict
            parameters:
                - name: PredictRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ServersPredictRequestBody'
                    required:
                        - uuid
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ServersPredictResponseBody'
                        required:
                            - ok
                            - error
                            - waiting
            schemes:
                - http
    /swaggerui/{path}:
        get:
            tags:
                - servers
            summary: Download ./swaggerui
            operationId: servers#/swaggerui/{*path}
            parameters:
                - name: path
                  in: path
                  description: Relative file path
                  required: true
                  type: string
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
                "404":
                    description: File not found
                    schema:
                        $ref: '#/definitions/Error'
            schemes:
                - http
definitions:
    Error:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Error response result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ServersGetHealthResponseBody:
        title: ServersGetHealthResponseBody
        type: object
        properties:
            msg:
                type: string
                description: message
                example: Tenetur cumque ipsum debitis ipsam velit est.
        example:
            msg: Reprehenderit nulla incidunt fuga omnis.
    ServersPredictRequestBody:
        title: ServersPredictRequestBody
        type: object
        properties:
            uuid:
                type: string
                description: unique userid
                example: "1"
                minLength: 1
        example:
            uuid: "1"
        required:
            - uuid
    ServersPredictResponseBody:
        title: ServersPredictResponseBody
        type: object
        properties:
            error:
                type: string
                description: error reason
                example: Libero rerum nam minima nulla soluta.
            ok:
                type: boolean
                description: operation successful?
                example: false
            recommendations:
                type: object
                properties:
                    crops:
                        type: string
                        example: Enim dolorem cum.
                    need_water:
                        type: boolean
                        example: true
                description: recommendations
                example:
                    crops: Voluptatibus et similique nulla quasi.
                    need_water: false
            waiting:
                type: boolean
                description: processing in progress
                example: false
        example:
            error: Quod ea assumenda placeat.
            ok: false
            recommendations:
                crops: Iure cumque voluptatem est atque quia.
                need_water: true
            waiting: true
        required:
            - ok
            - error
            - waiting
