openapi: 3.0.3
info:
    title: image
    description: crop yield monitor
    version: "1.0"
servers:
    - url: http://0.0.0.0:8081
paths:
    /fetch:
        get:
            tags:
                - servers
            summary: fetch servers
            operationId: servers#fetch
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FetchRequestBody'
                        example:
                            uuid: "1"
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Response'
                            example:
                                error: Cupiditate omnis.
                                image:
                                    - 66
                                    - 101
                                    - 97
                                    - 116
                                    - 97
                                    - 101
                                    - 32
                                    - 109
                                    - 111
                                    - 100
                                    - 105
                                    - 32
                                    - 112
                                    - 114
                                    - 97
                                    - 101
                                    - 115
                                    - 101
                                    - 110
                                    - 116
                                    - 105
                                    - 117
                                    - 109
                                    - 46
                                ok: false
    /healthz:
        get:
            tags:
                - servers
            summary: get health servers
            operationId: servers#get health
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Health'
                            example:
                                msg: Nisi itaque provident sed ipsum.
    /openapi3.json:
        get:
            tags:
                - servers
            summary: Download ./gen/http/openapi3.json
            operationId: servers#/openapi3.json
            responses:
                "200":
                    description: File downloaded
    /swaggerui/{*path}:
        get:
            tags:
                - servers
            summary: Download ./swaggerui
            operationId: servers#/swaggerui/{*path}
            parameters:
                - name: path
                  in: path
                  description: Relative file path
                  required: true
            responses:
                "200":
                    description: File not found
                "404":
                    description: File not found
    /upload:
        post:
            tags:
                - servers
            summary: upload servers
            operationId: servers#upload
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UploadRequestBody'
                        example:
                            image:
                                - 67
                                - 111
                                - 110
                                - 115
                                - 101
                                - 113
                                - 117
                                - 97
                                - 116
                                - 117
                                - 114
                                - 32
                                - 104
                                - 97
                                - 114
                                - 117
                                - 109
                                - 32
                                - 101
                                - 116
                                - 32
                                - 100
                                - 111
                                - 108
                                - 111
                                - 114
                                - 32
                                - 114
                                - 101
                                - 112
                                - 101
                                - 108
                                - 108
                                - 101
                                - 110
                                - 100
                                - 117
                                - 115
                                - 32
                                - 101
                                - 120
                                - 112
                                - 108
                                - 105
                                - 99
                                - 97
                                - 98
                                - 111
                                - 32
                                - 101
                                - 105
                                - 117
                                - 115
                                - 46
                            uuid: "1"
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Response'
                            example:
                                error: Labore fugit iure.
                                image:
                                    - 81
                                    - 117
                                    - 97
                                    - 115
                                    - 32
                                    - 113
                                    - 117
                                    - 105
                                    - 115
                                    - 46
                                ok: false
components:
    schemas:
        FetchRequestBody:
            type: object
            properties:
                uuid:
                    type: string
                    description: unique userid
                    example: "1"
                    minLength: 1
            example:
                uuid: "1"
            required:
                - uuid
        Health:
            type: object
            properties:
                msg:
                    type: string
                    description: message
                    example: Voluptatibus et nesciunt rerum.
            example:
                msg: Et quia non et.
        Response:
            type: object
            properties:
                error:
                    type: string
                    description: error reason
                    example: Necessitatibus blanditiis atque.
                image:
                    type: string
                    description: image in []byte
                    example:
                        - 73
                        - 116
                        - 97
                        - 113
                        - 117
                        - 101
                        - 32
                        - 105
                        - 108
                        - 108
                        - 111
                        - 46
                    format: binary
                ok:
                    type: boolean
                    description: operation successful?
                    example: true
            example:
                error: Sed explicabo.
                image:
                    - 86
                    - 101
                    - 110
                    - 105
                    - 97
                    - 109
                    - 32
                    - 101
                    - 120
                    - 101
                    - 114
                    - 99
                    - 105
                    - 116
                    - 97
                    - 116
                    - 105
                    - 111
                    - 110
                    - 101
                    - 109
                    - 32
                    - 101
                    - 116
                    - 32
                    - 115
                    - 105
                    - 110
                    - 116
                    - 46
                ok: true
            required:
                - ok
                - error
        UploadRequestBody:
            type: object
            properties:
                image:
                    type: string
                    description: image in byte array
                    example:
                        - 86
                        - 111
                        - 108
                        - 117
                        - 112
                        - 116
                        - 97
                        - 116
                        - 101
                        - 109
                        - 32
                        - 101
                        - 116
                        - 32
                        - 98
                        - 108
                        - 97
                        - 110
                        - 100
                        - 105
                        - 116
                        - 105
                        - 105
                        - 115
                        - 32
                        - 109
                        - 105
                        - 110
                        - 117
                        - 115
                        - 46
                    format: binary
                uuid:
                    type: string
                    description: unique userid
                    example: "1"
                    minLength: 1
            example:
                image:
                    - 84
                    - 101
                    - 109
                    - 112
                    - 111
                    - 114
                    - 101
                    - 32
                    - 105
                    - 117
                    - 115
                    - 116
                    - 111
                    - 32
                    - 118
                    - 105
                    - 116
                    - 97
                    - 101
                    - 46
                uuid: "1"
            required:
                - image
                - uuid
tags:
    - name: servers
      description: server handlers
